spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soomgo
    username: soomgo
    password: soomgo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#spring.jpa.show-sql: true